<?php

$title = 'Monthly Report';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class='filter box'>
    <form action="report/ip" method='POST'>
        <span class='title'>Filter By IP</span>
        <input type='text' name='ip'/>
        <input type='submit' value='Search'/>
    </form>
 </div>
 <hr/>
 <p><?php echo 'Amount of Landed IP: '.count($ipaddresses).' times';?></p>
 <table class="table">
 <tr>
     <th>IP</th>
     <th>City</th>
     <th>In</th>
     <th>Out</th>
 </tr>
 <?php foreach ($ipaddresses as $ipaddress) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($ipaddress->ip_address);?></td>
     <td><?php echo $this->escapeHtml($ipaddress->ip_city);?></td>
     <td><?php echo $this->escapeHtml($ipaddress->created_when);?></td>
     <td><?php echo $this->escapeHtml($ipaddress->end_when);?></td>
 </tr>
 <?php endforeach; ?>
 </table>