<?php

$title = 'Monthly Report';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class='filter box'>
    <form action="report/ip" method='POST'>
        <span class='title'>Filter By IP</span>
        <input type='text' name='ip'/>
        <input type='submit' value='Search'/>
    </form>
     <br/>
     <form action="report/station" method='POST'>
         <span class='title'>Fill Station Code</span>
        <input type='text' name='sid'/>
        in 
        <select name='month'>
            <?php 
                foreach($months as $order => $month)
                {
                    echo '<option value='.$order.'>'.$month.'</option>';
                }
                ?>
        </select>
        <input type='submit' value='Search'/>
     </form>
 </div>
 <hr/>
 <p><?php echo 'Amount of Landed IP: '.count($ipaddresses).' times';?></p>
 <table class="table">
 <tr>
     <th>IP</th>
     <th>Station</th>
     <th>City</th>
     <th>Land Time</th>
     
 </tr>
 <?php foreach ($ipaddresses as $ipaddress) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($ipaddress->ip_address);?></td>
     <td><?php echo $this->escapeHtml($ipaddress->station_code);?></td>
     <td><?php echo $this->escapeHtml($ipaddress->ip_city);?></td>
     <td><?php echo $this->escapeHtml($ipaddress->created_when);?></td>
 </tr>
 <?php endforeach; ?>
 </table>