<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="flowplayer-3.2.4.min.js"></script>    
<style> 
	.textb {font-family: "ms Sans Serif"; font-size: 11px; font-weight: normal ;text-decoration: none;color: #424242; }
	.textr {font-family: "ms Sans Serif"; font-size: 11px; font-weight: normal ;text-decoration: none;color: #cc0000; }
</style> 
<div align="center"> 
        <br /><br /><br />
        <table width="825px" border="0" cellpadding="1" cellspacing="5">
            <tr>
                <td  align="center" class="textr">
                    <b><u><img src="images/BannerLive.png" border=0></u></b>
                </td>
                <td>
                   <div id="player2" style="width:450px;height:300px"></div>
                   <script type="text/javascript">
                            live1();
                            function live1(){
                                var url="automediaradiolive";
                                var connectionUrl="rtmp://live.netdesignhost.com/automediaradiolive";
                                flowplayer("player2", "flowplayer.commercial-3.2.5.swf",{
                                    key: '#$84d81faf2eb521c8763',
                                    clip:{
                                        url:url,
                                        live: true,
                                        provider: 'rtmp', 
                                        bufferLength: '15',
                                        type: 'video'
                                    },            
                                    plugins: {
                                    rtmp:{
                                        url: 'flowplayer.rtmp-3.2.3.swf',
                                        netConnectionUrl: connectionUrl
                                    }
                                }
                                });
                            }
                   </script>                
                </td>
            </tr>
        </table>
    </div>